// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func CatchPokemonForm(isLoading bool, isPrimary bool, text string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-indicator=\"#loading\" class=\"poke-form-add\" hx-post=\"/api/v2/pokemons\" hx-swap=\"beforeend\" hx-target=\".pokemon-grid\" hx-indicator=\"#loading\" enctype=\"multipart/form-data\"><label class=\"poke-label\" htmlFor=\"name\">Pokemon Name</label> <input class=\"poke-input\" id=\"name\" type=\"text\" name=\"name\"> <label class=\"poke-label\" htmlFor=\"type\">Pokemon Type</label> <input class=\"poke-input\" id=\"type\" type=\"text\" name=\"type\"> <label class=\"poke-label\" htmlFor=\"level\">Pokemon Level</label> <input class=\"poke-input\" id=\"level\" type=\"text\" name=\"level\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Button(isLoading, isPrimary, text).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
